Add content to "Use the Dashboard"
space-ros/docs pull request #16
Opened 2022-12-20 21:03 UTC by audrow

This adds content covered in the demos.

There are a few things that I couldn't reproduce locally, like saving the annotations and uploading multiple archives. I added a note that these may not be working with the newest release. I'm not sure exactly where things were left.

2022-12-20 21:49 UTC, Ronoman requested changes

2022-12-20 21:49 UTC, Ronoman commented on source/How-To-Guides/Use-The-Dashboard.rst
> +- Track the dispositioning issues, including annotating them with links to bug reports in your dispositioning service of choice
"Track the dispositioning issues" -> "Track issues reported by static analysis tooling"

2022-12-20 21:49 UTC, Ronoman commented on source/How-To-Guides/Use-The-Dashboard.rst
> +You will also need to have SARIF data to view.
Might want to clarify that this happens through a `colcon build` then a `colcon test`. I've found that I need to either `--cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS` as an extra flag to build, or `set(COLCON_EXPORT_COMPILE_COMMANDS ON)` in the CMakeLists.txt for the respective package to get Cobra to run as well.

2022-12-20 21:49 UTC, Ronoman commented on source/How-To-Guides/Use-The-Dashboard.rst
> +Once you have the Space ROS Dashboard extension installed, you can open a SARIF file in Visual Studio Code and the Dashboard will automatically open.
"open a SARIF file" + " (found in `spaceros_ws/build/<package>/test_results`)"

2023-01-23 19:06 UTC, Ronoman commented on source/How-To-Guides/Use-The-Dashboard.rst
> +- Track the dispositioning issues, including annotating them with links to bug reports in your dispositioning service of choice
Resolved in ef6a1f48

2023-01-23 19:06 UTC, Ronoman commented on source/How-To-Guides/Use-The-Dashboard.rst
> +You will also need to have SARIF data to view.
Addressed in ef6a1f48

2023-01-23 19:07 UTC, Ronoman commented
LGTM!

2023-01-23 19:07 UTC, Ronoman approved these changes

2023-01-24 17:18 UTC, audrow commented
@Ronoman, I don't have write access on this repo. If you do, would you run the workflow and merge it in?

2023-01-24 17:25 UTC, Ronoman commented
@audrow Set it to run. You might want to check in with @nuclearsandwich about repo permissions, but it looks like your blocker here was just being a first-time contributor to the repo (if I read the error message right).

2023-01-25 22:38 UTC, merged